package pojos;
// Generated 24/10/2020 10:53:29 PM by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String emplDoc;
     private Empresa empresa;
     private String emplNombre;
     private int emplEdad;

    public Empleado() {
    }

    public Empleado(String emplDoc, Empresa empresa, String emplNombre, int emplEdad) {
       this.emplDoc = emplDoc;
       this.empresa = empresa;
       this.emplNombre = emplNombre;
       this.emplEdad = emplEdad;
    }
   
    public String getEmplDoc() {
        return this.emplDoc;
    }
    
    public void setEmplDoc(String emplDoc) {
        this.emplDoc = emplDoc;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getEmplNombre() {
        return this.emplNombre;
    }
    
    public void setEmplNombre(String emplNombre) {
        this.emplNombre = emplNombre;
    }
    public int getEmplEdad() {
        return this.emplEdad;
    }
    
    public void setEmplEdad(int emplEdad) {
        this.emplEdad = emplEdad;
    }




}


