package pojos;
// Generated 24/10/2020 10:53:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String empNombre;
     private String empDir;
     private String empTel;
     private Set empleados = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String empNombre, String empDir, String empTel) {
        this.empNombre = empNombre;
        this.empDir = empDir;
        this.empTel = empTel;
    }
    public Empresa(String empNombre, String empDir, String empTel, Set empleados) {
       this.empNombre = empNombre;
       this.empDir = empDir;
       this.empTel = empTel;
       this.empleados = empleados;
    }
   
    public String getEmpNombre() {
        return this.empNombre;
    }
    
    public void setEmpNombre(String empNombre) {
        this.empNombre = empNombre;
    }
    public String getEmpDir() {
        return this.empDir;
    }
    
    public void setEmpDir(String empDir) {
        this.empDir = empDir;
    }
    public String getEmpTel() {
        return this.empTel;
    }
    
    public void setEmpTel(String empTel) {
        this.empTel = empTel;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


